### ISSUE TITLE
Serialize default=colander.drop doesn't work with the Sequence

### ISSUE THREAD

**Issue by olegpidsadnyi** [Pylons/colander#144]
I had to subclass the Sequence and override the _impl(

and return the value if it is null or drop. otherwise it is trying to enumerate the drop or even catches it in the _validate

**Comment by mmerickel** [comment]
Is this fixed by #225? I'm assuming not since it's serialize instead of deserialize. Can you add a small code sample showing the issue?

**Comment by tisdall** [comment]
It should be fixed in #225.  That PR handled (if I remember correctly) both serialize and deserialize.
