### ISSUE TITLE
Any chance of getting a new release on pypi?

### ISSUE THREAD

**Issue by neilferreira** [Pylons/colander#169]
I would like to use this feature in a release and would like a new tag for my buildout file: https://github.com/Pylons/colander/commit/80058f11e907527c894a99bbbbf48e2f1782867d

Any chance you guys can publish a new release? I would like to avoid using mr.developer.

**Comment by tisdall** [comment]
Can we close this issue since a release has been made since this request, please?

**Comment by Natim** [comment]
Actually #157 is into master but not in the last release.

**Comment by Natim** [comment]
@tseaver Can you do a release will everything in master?

**Comment by tisdall** [comment]
@Natim you may want to open another issue...  The OP was posting about #123 and you're asking about something else.

**Comment by Natim** [comment]
Ok let's do that.

**Comment by Natim** [comment]
See #208
