### ISSUE TITLE
Support for bypassing default value injection.

### ISSUE THREAD

**Issue by AndreLouisCaron** [Pylons/colander#170]
Hi there!

I ran into this case today, and I can't figure out how to do it with Colander.

I defined a schema for validation of user input, say:

    class PersonSchema(colander.MappingSchema):
        name = colander.SchemaNode(colander.String())
        phone = colander.SchemaNode(colander.String(), missing=None)
        email = colander.SchemaNode(colander.String(), missing=None) 

All goes fine when I use this to create a new `Person` entry in the database.  However, I also need to allow users to update a subset of the information (e.g. the phone and/or the email) and leave the rest of their information intact.

I would like to re-use the same `PersonSchema` for the partial update input validation, but if I do that, colander will inject the schema nodes' `missing` value for all fields not provided in the input.

The current workaround is to perform validation, then do a second pass to remove the default values injected by deserialization.  Apart from being clumbersome, it adds unnecessary overhead.

Deserialization should have an argument that disables injecting missing values.

Just to be clear: the existing behavior is desired, but I'd like to *contextually* turn it off.

**Comment by tonthon** [comment]
First, you should use colander.drop as missing value for non-mandatory values with void defaults

```python
class PersonSchema(colander.MappingSchema):
    name = colander.SchemaNode(colander.String())
    phone = colander.SchemaNode(colander.String(), missing=colander.drop)
    email = colander.SchemaNode(colander.String(), missing=colander.drop) 
```

In case of edition, you can do something like that
```python
schema = PersonSchema().clone()
toremove = [ ]
for node in schema:
    if node.name not in submitted_datas_dict:
        toremove.append(node.name)
for name in toremove:
    del(schema[name])
```
this way you only keep edited datas in the resulting schema

**Comment by AndreLouisCaron** [comment]
@tonthon Thanks, I didn't know about `colander.drop`.  Neat.

I'm currently using something like this to validate incoming data in updates:
```
values = ...  # get from update.
sanitized_values = schema.deserialize(values)
sanitized_values = {k: v fo k, v in santized_values if k in values}
```

I think this is equivalent to your version.

However, my point is that I think using the same schema for both create & update is a fairly common use case and currently the only two options are:
1)  inject the defaults and the strip them manually after validation;
2) use a pair of schemas with identical definitions save for `missing=colander.drop`.

What I would like is to tell `.deserialize()` *not* to inject defaults when calling it.  Something like this:
```
class PersonSchema(colander.MappingSchema):
    name = colander.SchemaNode(colander.String())
    phone = colander.SchemaNode(colander.String(), missing='')
    email = colander.SchemaNode(colander.String(), missing='') 

# create.
values = ...  # get from create request.
values = schema.deserialize(values)

# update.
values = ...  # get from create request.
values = schema.deserialize(values, inject_missing=False)
```

**Comment by AndreLouisCaron** [comment]
Closing this as I've stopped using colander in new projects and started removing it elsewhere.
