### ISSUE TITLE
Email validator dot support

### ISSUE THREAD

**Issue by VladUlshin** [Pylons/colander#171]
Hi there!
Current  (v1.0b01)  Email validator uses Regex 
EMAIL_RE = "(?i)^[A-Z0-9._%!#$%&'*+-/=?^_`{|}~()]+@[A-Z0-9]+([.-][A-Z0-9]+)*.[A-Z]{2,8}$"

This allows dots to be first and last character of the email local part, as well as multiple dots. i.e. The following email are not RFC822 valid: .localpart@domain.com   localpart.@domain.com  localp..art@domain.com but passes colander Email validator.

change regex to something like this should eliminate the problem
EMAIL_RE = "(?i)(?!^[.]|._[.]@._|._[.]{2,}._)^[A-Z0-9._%!#$%&'*+-/=?^_`{|}~()]+@[A-Z0-9]+([.-][A-Z0-9]+)*.[A-Z]{2,8}$"

**Comment by imanhodjaev** [comment]
The problem is still there current regex allows dot before @ sign 

`EMAIL_RE = "(?i)^[A-Z0-9._%!#$%&'*+-/=?^_`{|}~()]+@[A-Z0-9]+([.-][A-Z0-9]+)*\.[A-Z]{2,22}$"
`

**Comment by tisdall** [comment]
Since so many people use Gmail and gmail allows the aforementioned email formats, it seems like a bad idea to mark valid routable emails as invalid.  I think if people want to do that, they should do that themselves and it shouldn't be a default of colander.

**Comment by imanhodjaev** [comment]
@tisdall Gmail validates and rejects these kind of emails with the following messages

```

The first character of your username should be a letter (a-z) or number.
The last character of your username should be a letter (a-z) or number.
```

**Comment by bertjwregeer** [comment]
Using regex to validate email addresses is futile. The standard allows so many things that the regex would explode.

See this page for the full regex generated from the grammar (BNF) included in the RFC standard for email:

http://www.ex-parrot.com/pdw/Mail-RFC822-Address.html

And even then it doesn't support the full standard...

Best bet is to make sure it contains at least some character before the @ symbol, and some characters after the @ symbol. Anything else will just have someone angry because their "email address" doesn't validate.

For example, requiring that an email contain a `.` after the @ symbol means you won't validate for these top-level domains that are dotless:

https://tools.ietf.org/html/rfc7085#page-4

```
AI mail is handled by 10 mail.offshore.AI.
   AX mail is handled by 5 mail.aland.net.
   CF mail is handled by 0 mail.intnet.CF.
   DM mail is handled by 10 mail.nic.DM.
   GP mail is handled by 10 ns1.worldsatelliteservices.com.
   GP mail is handled by 5 ns1.nic.GP.
   GT mail is handled by 10 ASPMX.L.GOOGLE.COM.
   GT mail is handled by 20 ALT1.ASPMX.L.GOOGLE.COM.
   GT mail is handled by 20 ALT2.ASPMX.L.GOOGLE.COM.
   GT mail is handled by 30 ASPMX2.GOOGLEMAIL.COM.
   GT mail is handled by 30 ASPMX3.GOOGLEMAIL.COM.
   GT mail is handled by 30 ASPMX4.GOOGLEMAIL.COM.
   GT mail is handled by 30 ASPMX5.GOOGLEMAIL.COM.
   HR mail is handled by 5 alpha.carnet.HR.
   IO mail is handled by 10 mailer2.IO.
   KH mail is handled by 10 ns1.dns.net.KH.
   KM mail is handled by 100 mail1.comorestelecom.KM.
   LK mail is handled by 10 malithi-slt.nic.LK.
   LK mail is handled by 20 malithi-lc.nic.LK.
   MQ mail is handled by 10 mx1-mq.mediaserv.net.
   PA mail is handled by 5 ns.PA.
   TT mail is handled by 10 ALT1.ASPMX.L.GOOGLE.COM.
   TT mail is handled by 1 ASPMX.L.GOOGLE.COM.
   UA mail is handled by 10 mr.kolo.net.
   VA mail is handled by 100 raphaelmx3.posta.VA.
   VA mail is handled by 10 raphaelmx1.posta.VA.
   VA mail is handled by 10 raphaelmx2.posta.VA.
   WS mail is handled by 10 mail.worldsite.WS.
   YE mail is handled by 10 mail.yemen.net.YE.
```

Not saying it's a good idea, but the regex proposed above is broken.

**Comment by jinty** [comment]
I wholeheartedly agree.

Additionally complex regexes expose you to a ReDoS attack
(https://en.wikipedia.org/wiki/ReDoS)

Pretty sure the "full" regex is vulnerable...

On Thu, Sep 01, 2016 at 10:40:16AM -0700, Bert JW Regeer wrote:
> Using regex to validate email addresses is futile. The standard allows so many things that the regex would explode.
> 
> See this page for the full regex generated from the grammar (BNF) included in the RFC standard for email:
> 
> http://www.ex-parrot.com/pdw/Mail-RFC822-Address.html
> 
> And even then it doesn't support the full standard...
> 
> Best bet is to make sure it contains at least some character before the @ symbol, and some characters after the @ symbol. Anything else will just have someone angry because their "email address" doesn't validate.
> 
> For example, requiring that an email contain a `.` after the @ symbol means you won't validate for these top-level domains that are dotless:
> 
> https://tools.ietf.org/html/rfc7085#page-4
> 
> ```
> AI mail is handled by 10 mail.offshore.AI.
>    AX mail is handled by 5 mail.aland.net.
>    CF mail is handled by 0 mail.intnet.CF.
>    DM mail is handled by 10 mail.nic.DM.
>    GP mail is handled by 10 ns1.worldsatelliteservices.com.
>    GP mail is handled by 5 ns1.nic.GP.
>    GT mail is handled by 10 ASPMX.L.GOOGLE.COM.
>    GT mail is handled by 20 ALT1.ASPMX.L.GOOGLE.COM.
>    GT mail is handled by 20 ALT2.ASPMX.L.GOOGLE.COM.
>    GT mail is handled by 30 ASPMX2.GOOGLEMAIL.COM.
>    GT mail is handled by 30 ASPMX3.GOOGLEMAIL.COM.
>    GT mail is handled by 30 ASPMX4.GOOGLEMAIL.COM.
>    GT mail is handled by 30 ASPMX5.GOOGLEMAIL.COM.
>    HR mail is handled by 5 alpha.carnet.HR.
>    IO mail is handled by 10 mailer2.IO.
>    KH mail is handled by 10 ns1.dns.net.KH.
>    KM mail is handled by 100 mail1.comorestelecom.KM.
>    LK mail is handled by 10 malithi-slt.nic.LK.
>    LK mail is handled by 20 malithi-lc.nic.LK.
>    MQ mail is handled by 10 mx1-mq.mediaserv.net.
>    PA mail is handled by 5 ns.PA.
>    TT mail is handled by 10 ALT1.ASPMX.L.GOOGLE.COM.
>    TT mail is handled by 1 ASPMX.L.GOOGLE.COM.
>    UA mail is handled by 10 mr.kolo.net.
>    VA mail is handled by 100 raphaelmx3.posta.VA.
>    VA mail is handled by 10 raphaelmx1.posta.VA.
>    VA mail is handled by 10 raphaelmx2.posta.VA.
>    WS mail is handled by 10 mail.worldsite.WS.
>    YE mail is handled by 10 mail.yemen.net.YE.
> ```
> 
> Not saying it's a good idea, but the regex proposed above is broken.
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Pylons/colander/issues/171#issuecomment-244154725

-- 
Brian Sutherland

**Comment by tisdall** [comment]
@imanhodjaev - well, I tested it 2 years ago, so it may have changed

**Comment by imanhodjaev** [comment]
@tisdall @jinty I agree that it is much safe to check for presence of @ sign in the address and make some checks if it contains username and domain part.
It is already done in Django https://github.com/django/django/blob/master/django/core/validators.py#L170 so may be we can use the same approach?

**Comment by bertjwregeer** [comment]
This was fixed by using the same email regex validation as the WhatWG HTML standard.

**Comment by Rogalek** [comment]
I think it didn't fix original issue. Still got problems with dot before @ sign.
```
exception | SMTPRecipientsRefused: {'ab.@abc.pl': (501, b'Invalid command or cannot parse to address')}
```

**Comment by stevepiercy** [comment]
@Rogalek please see https://github.com/Pylons/colander/issues/330#issuecomment-511099779

**Comment by jenstroeger** [comment]
Bit late to the party but regarding the mention of Gmail above, please note that [dots don’t matter in Gmail addresses](https://support.google.com/mail/answer/7436150).

**Comment by Rogalek** [comment]
@stevepiercy ok, so I will just define my validators, thanks :)

@jenstroeger dot matter only if it is just before `@` for example: `abc.@gmail.com`
