### ISSUE TITLE
SchemaNode subclasses title being ignored

### ISSUE THREAD

**Issue by Mr-F** [Pylons/colander#174]
It seems when you create a custom SchemaNode as per the example in the document i.e.

```
class EmailSchemaNode(colander.SchemaNode):
    schema_type = colander.String
    title = 'Email Address'
    validator = colander.Email()
```

and then use it like this

```
class MySchema(colander.MappingSchema):
    email = EmailSchemaNode()
```

the label displays "Email" instead of "Email Address".  I would have thought that specify the title in the node would mean it would be used as the default value, or am I missing something

**Comment by tisdall** [comment]
hadn't even noticed this issue before...  ;) 

fixed with #239
