### ISSUE TITLE
[Proposal] Add logs to colander

### ISSUE THREAD

**Issue by jaseemabid** [Pylons/colander#200]
I've encountered cases when colander silently drops attributes because I forgot
to white-list them in validation classes. It would be helpful to get logs from
colander of the form

```
- [DEBUG] Validating user schema 
- [DEBUG] Received attributes [id, name, age, evil]
- [DEBUG] Validated attributes [id, name]
- [DEBUG] Validation failed for attributes [age]
- [DEBUG] Dropped unknown attributes [evil]
```

Any comments? 
If this is OK, I'll try to do patch over the weekend.

**Comment by mmerickel** [comment]
colander's deserialization is stateless and so there is not a place to put these errors... meaning even if we add logging there's nothing you can do with the info. I think this indicates that you will almost always need to handle this case outside of colander if you want to do any real work versus just seeing a log message.
