### ISSUE TITLE
Any chance of getting a new release on pypi?

### ISSUE THREAD

**Issue by Natim** [Pylons/colander#208]
They are lots of commits in master that are not in the last release.
Could we do a release with the last master please?

See https://github.com/Pylons/colander/compare/1.0...master

**Comment by Natim** [comment]
One I'd like to use is #157

**Comment by Natim** [comment]
Any updates here?

**Comment by jgelens** [comment]
bump?

**Comment by BartSaelen** [comment]
A new release would be nice

**Comment by stevepiercy** [comment]
As listed on PyPI, the two maintainers are @tseaver and @mcdonc (tseaver, chrism). I don't know whether more maintainers are being sought.

Offering to help and contribute to make a release might be more effective than merely asking for a release.

As far as what is needed to make a release, I couldn't find anything more specific than the default Pylons Project guidelines. Pyramid has a [well documented release process](https://github.com/Pylons/pyramid/blob/master/RELEASING.txt).

**Comment by koenedaele** [comment]
We (https://github.com/OnroerendErfgoed) would like a new release to make use of the updated Dutch translations and the Internationalization features. 

Is there anything we can do to help make it happen?

**Comment by tisdall** [comment]
@koenedaele - I think @stevepiercy was pretty clear...  However, I think all a regular user can do is create a PR that has incremented the version number in all the appropriate spots.  Then you'll have to wait for someone with access to do all the other things listed.  You can see from the date on the first post of this issue that you'll likely be waiting a long time.

If you really want to use it, just pull it from the git repo.  You'll have to make sure you do `setup.py develop` or install it after first installing `setuptools-git` as there's no MANIFEST file.

**Comment by stevepiercy** [comment]
@koenedaele an abridged version of the Pyramid release process was recently added to [deform](https://github.com/Pylons/deform/blob/master/RELEASING.txt), from which you may adapt the process to build an sdist for colander for immediate personal use.

> You can see from the date on the first post of this issue that you'll likely be waiting a long time.

My diplomacy on this matter has now evaporated. Enough! @tisdall can you pick winning Powerball numbers with your predictive ability, too? Why should a maintainer perform work for no pay, thanks, or any benefit whatsoever, but instead receive presumptuous and snippy comments like this?

Maintaining software is demanding, and its users are unreasonably more so.

**Comment by tisdall** [comment]
@stevepiercy - I'm sorry if it came off that way...  My point was not an attack at the maintainers but to point out to @koenedaele that it'd be more prudent to use the git version instead of hoping/waiting for a new release.  This is especially so because what can be provided via a PR towards a new release is only a small fraction of the whole (basically it's incrementing the version) and there's still a large chunk of work for a maintainer to do (on top of checking the content of the PR).  Also, someone offering to do the rest and ask for access is going to be met with a "no", right?

**Comment by Natim** [comment]
> Offering to help and contribute to make a release might be more effective than merely asking for a release.

I am 100% wanting to contribute and to publish a new version of colander on pypi. Do not hesitate to add me as an admin in PyPi as well as in the github repository, it would be my pleasure.

I think as a community we have to fix this recurring issue.
Why not doing release automatically as soon as a PR gets merged into master?

There is an initiative going on about this: https://jezdez.com/blog/launching-jazzband
If you feel like you don't have time to spend on colander anymore, why not moving it there?

If you publish a library that people are using, not releasing it can be a blocker for them, really.
If you don't have time to release it yourself that's not a problem, but please give them the power to do it so they can continue to work with and improve the project.

**Comment by bertjwregeer** [comment]
This is being worked on. Please standby.

**Comment by stevepiercy** [comment]
Thanks for the reference to Jazzband, @Natim. We're evaluating options like this.

I'd also like to acknowledge and show my appreciation for those who have expressed interest in helping out. We want to make sure that we do things correctly, which also means agreeing upon those things. For example, should a maintainer provide at least two releases with deprecation warnings of backward incompatible changes? [Pyramid has a policy on this and other issues](http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/upgrading.html), but it's not clear whether all other projects under Pylons Project should adopt this policy.

**Comment by mmerickel** [comment]
1.1 was released last night. Thanks folks.

**Comment by leplatrem** [comment]
Everyone, thanks a lot for your efforts!

**Comment by tisdall** [comment]
Special thanks to @mmerickel, he ripped through a backlog of PR's and issues!

**Comment by koenedaele** [comment]
Thanks to everybody for making this happen! I'm fully aware that creating and maintaining open source software can be hard and unrewarding at times. Apologies if I ever made it sound like people should do it for free with no appreciation whatsoever. We were going to package the master version up ourselves for internal use and I was wondering if some of that work might be contributed back to the project.

Again, thank you all!

**Comment by Natim** [comment]
Yes thank you all :)
