### ISSUE TITLE
Add py.test as testing runner/framework

### ISSUE THREAD

**Issue by sandhujasmine** [Pylons/colander#210]
In April the pytest team is holding "adopt pytest month" to encourage projects to consider using pytest, by pairing open source projects with experienced pytest helpers. It doesn't matter if your test suite right now is barely-there or has 100% code coverage - we think pytest can improve almost any testing situation, and we would like to invite this project to take part.
For more information and to sign up please check out: http://pytest.org/latest/adopt.html

**Comment by tseaver** [comment]
While we don't want to block folks using `py.test` for their own projects, we're pretty well established with the tools we use now (`tox` for the overall cross-version runner, `setup.py test` for minimal tests, `nose --with-coverage` for coverage).

**Comment by mcepl** [comment]
May I ask for reopening of this issue. I am a maintainer of Python packages in openSUSE, and I am on my crusade of eliminating nose1 from our distribution. When I look at its repository on https://github.com/nose-devs/nose, the last release 1.3.7 was on 2 Jun 2015, and even the last commit on the master branch was on 4 Mar 2016.

I have tried and failed both with pytest ([complete log of the build](https://github.com/Pylons/colander/files/4482896/_log-pytest.txt) and nose2 ([log](https://github.com/Pylons/colander/files/4482897/_log-nose2.txt)) and both of them end with rather nonsensical error:
```
[   39s] E       AttributeError: 'TestFunctional' object has no attribute '_makeSchema'
```
Do you have any idea, what’s going on, please?

**Comment by bertjwregeer** [comment]
@mcepl I am more than happy to re-open this, however at this time unless someone takes up the time and effort to port the test suite to pytest it won't happen for a while.

**Comment by bertjwregeer** [comment]
@mcepl quick look at the source code, and it looks like `TestFunctional` sub-classes `object` and would normally not be picked up by `nose` or `unittest`, however `pytest` seems to pick it up as a class to test.

It is used as a base class for various other tests.

```
%s/TestFunctional/FunctionalBase/g
```

in `olander/tests/test_colander.py` will likely allow the test suite to run without issues.

**Comment by mcepl** [comment]
Thank you.
[This patch](https://github.com/Pylons/colander/files/4491790/fix-tests.patch.txt) solved the problem, but I guess you have something equivalent in #335.

**Comment by bertjwregeer** [comment]
Yeah, that was the same as this patch: https://github.com/Pylons/colander/pull/335/commits/a75fb4d1595c5a0bdda4f52f45d7a41a66b76415
