### ISSUE TITLE
Returned HTTP status code for invalid scehma.

### ISSUE THREAD

**Issue by andrewjburnett** [Pylons/colander#213]
If I am using Colander for schema validation, is it possible to change the returned http status code when there is an error? For example, if my colander schema is invalid, how can I capture this error and return its message along with a status code of my choosing. For example, how would I go about returning a different status code, say '422 Unprocessable Entity', for this type of invalid schema error?

**Comment by leplatrem** [comment]
I believe using stackoverflow would be more appropriate for user assistance :)

Something like that could do it (*adjust it to the web framework you use*):

```python
try:
    schema.deserialize(data)
except colander.Invalid:
    response.status_code = 422
```

**Comment by andrewjburnett** [comment]
Sorry about that. Thanks for the assistance though!
