### ISSUE TITLE
Feature request: Internationalization

### ISSUE THREAD

**Issue by AnderUstarroz** [Pylons/colander#216]
How can I translate the error messages from the [colander](http://docs.pylonsproject.org/projects/colander/en/latest/) validators? The documentation just says that it's possible. 

    def valid_text(node, value):
            raise Invalid(node, u"Some error message")
    
    class form(colander.MappingSchema):
        name = colander.SchemaNode(colander.String(), validator=valid_text)

I know that [deform](http://deform.readthedocs.org/en/latest/) does it already but I need to use **colander** on his own.

**Comment by leplatrem** [comment]
I believe this was addressed by @amarandon in PR #157.
AFAIK it was merged but not released.

**Comment by AnderUstarroz** [comment]
After applying his commit it works like a charm. Thanks @leplatrem!

**Comment by tisdall** [comment]
Shouldn't this issue be closed then?

**Comment by leplatrem** [comment]
I wouldn't have closed it since it was not released on pypi :)

**Comment by tisdall** [comment]
Maybe just add a :+1: to #208...  it's also asking for the same thing to be released.

**Comment by stevepiercy** [comment]
:+1: are loathed. Better to just mention a maintainer directly and request a release, assuming there is a maintainer.
