### ISSUE TITLE
Support for selects with multiple values

### ISSUE THREAD

**Issue by AnderUstarroz** [Pylons/colander#219]
Looks like colander cannot deserialize properly  the arrays generated by multiple selects like the ones used in [Bootstrap](http://formvalidation.io/examples/bootstrap-multiselect/).
When a form sends a POST request with multiple options selected like the following:

```
<form method="post">   
    <select class="form-control" name="browsers" multiple>
                <option value="chrome">Google Chrome</option>
                <option value="firefox">Firefox</option>
                <option value="ie">IE</option>
                <option value="safari">Safari</option>
                <option value="opera">Opera</option>
                <option value="other">Other</option>
    </select>
    <input type="submit">
</form>
```
Colander will only deserialize the last value of the selected options from the received array.

**Comment by tisdall** [comment]
I'm not sure what you're doing since colander doesn't directly handle form processing, but here's an example of it working just fine:  http://deform2demo.repoze.org/select_with_multiple/

**Comment by AnderUstarroz** [comment]
I'm using colander for deserializing and validating some  forms in which I cannot use deform. Validating forms with just colander is easy enough. About your example, the deform widget is the one handling the multiple-selections. Anyway I see your point, Colander is just about serializing/deserializing if I want more advanced form features I should develop them myself or use deform or similars.
