### ISSUE TITLE
tox docs test doesn't cover pdf

### ISSUE THREAD

**Issue by tisdall** [Pylons/colander#222]
Related to #221:  The pdf's were failing to generate on readthedocs and this was causing both the html and pdf version to fail to be updated.

I'm thinking someone needs to update the test to include PDF generation.  I'm not really sure how to do that properly, though...  It's likely an issue with all the Pylons projects too.

**Comment by stevepiercy** [comment]
First this is a RTD issue, not a colander issue.

It appears that RTD added PDF generation as a default setting around 4 months ago. Out of all the Pylons Projects, I think only Pyramid supports PDF generation and has done so for years, but the configuration to get it right with RTD is not trivial. Given that HTML generates just fine on RTD, I'm going to close this issue as "won't fix", although anyone who wants to take the time to add PDF generation support at RTD is more than welcome to take it on. The first step would be to get PDF to build locally.

**Comment by tisdall** [comment]
Okay, but unfortunately with the current setting, a failed PDF build means the html also fails.  I can't seem to see any way of shutting off PDF creation either.

The reason for testing for PDF build would be the same reason for testing the html build... if either fails the docs will fail to update on the server.

**Comment by stevepiercy** [comment]
See https://github.com/Pylons/colander/pull/221#issuecomment-99473311
