### ISSUE TITLE
Support for Thrift or Avro

### ISSUE THREAD

**Issue by ecesena** [Pylons/colander#255]
Any plan to support either Thrift or Avro for schema definition? Or, any argument against? Thanks, E.

**Comment by mmerickel** [comment]
That's out of scope for colander's core but certainly you could consider writing an adapter to generate a schema object from one of those definitions. There is a similar project named colanderalchemy for converting sqlalchemy objects into colander schemas.

**Comment by ecesena** [comment]
Thanks a lot, I'll look into it.
