### ISSUE TITLE
RegEx validator matches only from the beginning of the string

### ISSUE THREAD

**Issue by jenstroeger** [Pylons/colander#277]
The current version of Colander’s `RegEx()` validator calls Python’s [`match()`](https://docs.python.org/3/library/re.html#re.match) function, see source [here](https://github.com/Pylons/colander/blob/5e4d2c6fa4f6dc86465516ee93f45be61539c7e4/colander/__init__.py#L345). That function matches only the beginning of the string, not the entire given string.

This should be documented as it impacts the regular expressions used.

As of Python 3.4, [`fullmatch()`](https://docs.python.org/3/library/re.html#re.fullmatch) should be considered to replace the call to `match()`.

**Comment by tseaver** [comment]
@jenstroeger Thanks for the report.  Can you suggest a rewording of the [`Regex` docstring](https://github.com/Pylons/colander/blob/5e4d2c6fa4f6dc86465516ee93f45be61539c7e4/colander/__init__.py#L318-L320) which would make it clearer that the value is checked using `.match()`?

**Comment by jenstroeger** [comment]
How about something like:

    Initialize it with the string regular expression ``regex``
    that will be compiled and matched against the beginning
    of ``value`` when validator is called. (Use ``^`` and ``$``
    to enclose the regular expression to match a whole string.)

**Comment by stevepiercy** [comment]
I pulled this from the Python docs and expanded on @jenstroeger's version.

```rst
        Initialize it with the string regular expression ``regex`` that will
        be compiled and matched against ``value`` when validator is called. It
        uses Python's :py:func:`re.match`, which only matches at the beginning
        of the string and not at the beginning of each line. To match the
        entire string, enclose the regular expression with ``^`` and ``$``.
```

**Comment by jenstroeger** [comment]
Yup, sounds good to me, @stevepiercy.
