### ISSUE TITLE
GlobalObject serialization incorrect?

### ISSUE THREAD

**Issue by jay-hennen** [Pylons/colander#287]
```
from colander import GlobalObject, SchemaNode
import collections

sn = SchemaNode(typ=GlobalObject(collections))
ser = sn.serialize(collections.OrderedDict)
print ser
    'OrderedDict'
des = sn.deserialize(ser)
    Invalid: {'': u'The dotted name "OrderedDict" cannot be imported'}
ser = '.OrderedDict'
des = sn.deserialize(ser)
    collections.OrderedDict
```

To summarize, the serialization only returns the `__class__` of a type, without a '.' appended. To get the class from the deserialize function it needs to be given a dotted class name, in which case the behavior seems to be appropriate.

Am I mistaken in how serialize/deserialize are supposed to work in this situation? Please advise.

**Comment by mmerickel** [comment]
It looks like this should be using a combination of `__module__` and `__name__` to compute the importable object string. Currently there is only a test for a module and not a class so this should be improved.

Any chance you're interested in supplying a patch?

**Comment by jay-hennen** [comment]
Yeah, I'm interested. If I understand correctly, you are referring to using both `__module__` and `__name__` during serialization to compute the right string, correct? 



Just to be clear, what is the resulting relationship between the appstruct, serialize() and the GlobalObject().package attribute? See the example below:
```
from colander import GlobalObject, SchemaNode
import collections
from collections import OrderedDict

sn = SchemaNode(typ=GlobalObject(collections))
print sn.typ.package
    <module 'collections' from ... >

print sn.serialize(collections.OrderedDict)
    **'.OrderedDict' OR 'collections.OrderedDict' ??**

print sn.serialize(OrderedDict)
    **'.OrderedDict' ??**
```

Also, what of the two naming schemes (zope_dotted versus pkg_resources)?

**Comment by mmerickel** [comment]
So there's a couple things to note. I'll start with answering your question about the `GlobalObject` usage. `GlobalObject` is for serializing / deserializing references to globally-importable objects. This would be something you defined at module-level that can be imported - I imagine it could be a class, an instance or a function. For example

```
# mypackage.MY_OBJECTS
MY_OBJECTS = OrderedDict(...)
```

This `MY_OBJECTS` object is importable as `mypackage.MY_OBJECTS`. You can also perform a relative import if you use `GlobalObject(mypackage)`. Then deserialize would accept `.MY_OBJECTS` as well as `mypackage.MY_OBJECTS` and `mypackage:MY_OBJECTS`.

The `serialize` appears to be intended to always return an absolute import whereas the `package` argument controls what is accepted for deserialize.

> Also, what of the two naming schemes (zope_dotted versus pkg_resources)?

There are two similar specs for how to import an object from a string. Either a simple dotted string like `mypackage.MY_OBJECTS` or using the pkg_resources style which is a dotted string to the module and then colon (:) with the object inside the module after... such as `mypackage:MY_OBJECTS`.

At the end of the day I think `GlobalObject` has very limited use and you may not actually want to use it but that's your call.

> If I understand correctly, you are referring to using both __module__ and __name__ during serialization to compute the right string, correct?

Yeah the idea is to take an arbitrary class/function/object and figure out its importable path which is not particularly simple in Python so it requires a bit of guesswork. It's not possible afaik to figure out the importable path of an object... only the importable path of its class. For this reason I think `GlobalObject.serialize` itself probably has very limited usage.

**Comment by jay-hennen** [comment]
> The serialize appears to be intended to always return an absolute import whereas the package argument controls what is accepted for deserialize.

So the serialize should always return the entire absolute import for the object? In the example above then it would always return 'collections.OrderedDict' 

> At the end of the day I think GlobalObject has very limited use and you may not actually want to use it but that's your call.

It seems to fit my use case well so far, aside from the behavior at hand.

**Comment by mmerickel** [comment]
> So the serialize should always return the entire absolute import for the object? In the example above then it would always return 'collections.OrderedDict'

This looks to be the case... my original impression of the api was that it would not. There are no real tests for the serialization side of the api so it is a little hard to deduce the goal. To me it should, at least, support `__module__` and `__name__` and possibly `__qualname__` but attempting to make it relative or anything is not something I would consider important.
