### ISSUE TITLE
passing a float to colander.Integer does not throw exception

### ISSUE THREAD

**Issue by cecemel** [Pylons/colander#292]
When passing a float value (e.g. 1.21) to a colander.Integer node, no exception is thrown.
I am not sure of the expected behaviour though...

Version: 1.3.3

**Comment by bertjwregeer** [comment]
Internally the conversion is passed to `int()`, and Python parses the string and returns an integer: https://github.com/Pylons/colander/blob/master/colander/__init__.py#L1417

Floats will silently truncated.

Adding some extra protection wouldn't be entirely out of line IMHO.

**Comment by bertjwregeer** [comment]
@cecemel Use `Integer(strict=True)` for this to correctly raise an exception if passed a float instead of a real integers.
