### ISSUE TITLE
Improve naive/aware DateTime objects and documentation

### ISSUE THREAD

**Issue by jenstroeger** [Pylons/colander#293]
I think it would help to clarify [in the documentation](https://docs.pylonsproject.org/projects/colander/en/latest/api.html#colander.DateTime) that a deserialized `datetime` object is by default _aware_ (i.e. its `tzinfo` attribute is set to a timezone object provided by the [`pytz`](https://pypi.python.org/pypi/pytz) non-standard library) rather than being _naive_ (i.e. its `tzinfo` attribute is `None`).

In this context, **normalizing** while deserializing an _aware_ `datetime` into a _naive_ datetime would be useful for those applications which operate purely on _naive_ `datetime` objects. For example, deserializing a string with `+00:00` as a timezone might simply strip `tzinfo`, whereas other offsets ought to be added to a _naive_ `datetime` using a [`timedelta`](https://docs.python.org/3/library/datetime.html#datetime.timedelta) derived from the offset.

**Comment by tseaver** [comment]
@jenstroeger Hmm, the [current docs]() seem to me to make it clear that naive datetimes get a timezone applied using the `default_tzinfo` attribute.  Users who want to suppress that conversion need to pass `tz_info=None` when constructing the schema node / type.  E.g.:

```python
import colander

class Example(colander.Schema):
    naive_stamp = colander.SchemaNode(
        colander.DateTime(default_tzinfo=None),
    )
```
Please feel free to reopen if I've missed the point here.
