### ISSUE TITLE
How to validate dependency between validated schema data

### ISSUE THREAD

**Issue by jenstroeger** [Pylons/colander#298]
(Based on [this Stackoverflow question](https://stackoverflow.com/questions/45627443/colander-schema-validation-validate-dependency-between-data) for lack of another documented place to ask Colander related questions.)

Suppose I have a [Colander](https://docs.pylonsproject.org/projects/colander/en/latest/) schema that specifies a date and time range:
```python
    class DateRangeSchema(colander.MappingSchema):
        start = colander.SchemaNode(
            colander.DateTime(),
            missing=None, # Can’t be a callable?
            )
        end = colander.SchemaNode(
            colander.DateTime(),
            missing=None, # Can’t be a callable?
            )
```
I would like to check that `start > end`, essentially adding a “post-validation hook” (the opposite of a [preparer](https://docs.pylonsproject.org/projects/colander/en/latest/interfaces.html#colander.interfaces.Preparer)) which allows me to enforce further constraints on individually valid data items _in relation to each other_.

How would I specify such dependencies?

**Comment by tseaver** [comment]
Override `validator` on your `DateRangeSchema` class, e.g.:

```python
class DateRangeSchema(colander.MappingSchema):
    start = colander.SchemaNode(
        colander.DateTime(),
        missing=None, # Can’t be a callable?
        )
    end = colander.SchemaNode(
        colander.DateTime(),
        missing=None, # Can’t be a callable?
        )
    def validator(self, node, cstruct):
          start = cstruct['start']
          end = cstruct['end']
          if end is not None and start is not None and end <= start:
              raise colander.Invalid(node, 'end must fall after start')
```

**Comment by jenstroeger** [comment]
@tseaver, thank you!

Also, can I assign values to the `cstruct`, for example:
```python
    def validator(self, node, cstruct):
        if cstruct['start'] is None:
            cstruct['start'] = datetime.utcnow()
        if cstruct['end'] is None:
            cstruct['end'] = datetime.utcnow()
        start = cstruct['start']
        end = cstruct['end']
        if end <= start:
            raise colander.Invalid(node, 'end must fall after start')
```
Basically enforcing default values (assuming that `missing` can’t take callables, which I think it can’t).

**Comment by tseaver** [comment]
@jenstroeger See the [binding doc](http://colander.readthedocs.io/en/latest/binding.html).

**Comment by jenstroeger** [comment]
@tseaver, in the documentation’s example (e.g. the deferred date `deferred_date_missing `) the callable is invoked at _bind_-time, but not at validation time. So the `default_date` value is the `bind()`’s call timestamp, not when an item is validated. Thus I’d need to `bind()` whenever I need a schema instance with the current timestamp?

Or am I misreading the code?
