### ISSUE TITLE
Email validator accepting "invalid@email"

### ISSUE THREAD

**Issue by bachirelkhoury** [Pylons/colander#330]
Currently, the regex is allowing an email **invalid@email** with no dots. 

Perhaps related to #171 request.

**Comment by stevepiercy** [comment]
Can you double-check? Try [this regex tester](https://regex101.com/r/aVo8H8/1/) which is a copy-paste of the [current regex](https://github.com/rbu/colander/blob/master/colander/__init__.py#L352).

**Comment by bachirelkhoury** [comment]
hmm... that regex is better but it's in a fork.
I'm using the [latest colandar 1.7.0](https://docs.pylonsproject.org/projects/colander/en/latest/changes.html#id1) which has the below regex:

`# Regex for email addresses.
#
# Stolen from the WhatWG HTML spec:
# https://html.spec.whatwg.org/multipage/input.html#e-mail-state-(type=email)
#
# If it is good enough for browsers, it is good enough for us!
EMAIL_RE = (
    r"^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9]"
    r"(?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9]"
    r"(?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$"
)
`
is that not the official version? perhaps I'm missing something. Thanks @stevepiercy

**Comment by stevepiercy** [comment]
Oh, sorry. You are correct. You found the current implementation.

Technically `foo@bar` is valid. If you want different requirements, you will have to [define a new validator](https://docs.pylonsproject.org/projects/colander/en/latest/extending.html#defining-a-new-validator) or override it like in the fork to which I unintentionally linked. I doubt we'll deviate from the WhatWG spec.

**Comment by bachirelkhoury** [comment]
All good thanks for your help @stevepiercy
