### ISSUE TITLE
dynamic dictionary

### ISSUE THREAD

**Issue by keith6014** [Pylons/colander#331]
I tried doing this in Marshmallow but was too cumbersome and was wondering if colander can do this.
```json
{
  "title": "arba",
  "srv": {
    "A": [
      {
        "server:export0": "/mp1",
        "server:export1": "/mp2"
      }
    ],
    "B": [
      {
        "server:export1": "/mnt/ffee"
      }
    ]
  }
}
````
* "title" is mandatory. Must be string
* "srv" will be dynamic. Must be a string. Dynamic means, it will be called "srv", "foo","bar", or whatever
* "A" & "B" will be dynamic. Must be string

is there a way to use Colander to validate this?

**Comment by stevepiercy** [comment]
Please see https://pylonsproject.org/community-support.html

> GitHub is the least desirable option. Posting a request for general support to the project's GitHub issue tracker reaches the smallest audience, and takes time away from fixing bugs and adding features. Please don't be "that person".

Otherwise see https://docs.pylonsproject.org/projects/colander/en/latest/extending.html#defining-a-new-validator
