### ISSUE TITLE
What about locale directory

### ISSUE THREAD

**Issue by iinov** [Pylons/colander#339]
Hello,
I retrieve the new 1.8.0 release and I no longer have a locale directory. Is it normal?
Best regards,
Patrick PIERRE

**Comment by mmerickel** [comment]
It's not normal. I may have messed up the release.

**Comment by iinov** [comment]
Ok. I am waiting for the next release.
Thanks for your very quick answer.

**Comment by stevepiercy** [comment]
Reopening until this is resolved. I checked the download from PyPI, and `locale` is not included.

**Comment by stevepiercy** [comment]
Closed with release of 1.8.1

**Comment by iinov** [comment]
Very strange, I still don't have a `locale` directory with 1.8.1 and python3.

**Comment by mmerickel** [comment]
I'm so sorry, apparently I was way too hasty in these releases and didn't check my work. Steve noticed I typoed the fix but I thought it still worked. Guess it didn't. We moved from setup.py to setup.cfg and some directives weren't copied over properly and we didn't test it well enough. Excuses, anyway I promise it is fixed now in 1.8.2.

**Comment by stevepiercy** [comment]
Interesting. The tar.gz was fine in 1.8.1, but I did not check the wheel. I guess that typo had a negative impact after all.

**Comment by iinov** [comment]
It now works perfectly. Thanks.
