### ISSUE TITLE
ICANN prohibits dotless email domains

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [Pylons/colander#342]
As you can read [here](https://www.icann.org/news/announcement-2013-08-30-en) dotless email domain names are prohibited.
I think the validator should be updated accordingly.

**Comment by stevepiercy** [comment]
See https://github.com/Pylons/colander/issues/171#issuecomment-244154725 and https://github.com/Pylons/colander/issues/330#issuecomment-511099779 for why it is the way it is and that you will need to implement a custom validator.

**Comment by bertjwregeer** [comment]
ICANN doesn't control the ccTLD's, and as such there are a couple with dotless emails, as seen in the linked posts from @stevepiercy.

I'm sorry,  but we will not be changing this at this time. If you want to validate if an email is valid, you'll want to do a very different dance than it satisfying a simple regex, you can try the following:

1. See if the domain has MX records, then assume it can receive email.
2. See if the server has A/AAAA records (follow CNAME's as necessary) and connect to port 25
3. Actually send an email

That's the only and best way to know if an email is valid.
