### ISSUE TITLE
Deferred nodes lose their custom names

### ISSUE THREAD

**Issue by Wim-De-Clercq** [Pylons/colander#345]
Code with bug:
```python
import colander

@colander.deferred
def deferred_node(node, bindings):
    return colander.SchemaNode(colander.Str(), name='key-2', missing=colander.drop)


class MySchema(colander.Schema):
    key1 = colander.SchemaNode(colander.Str(), name='key-1', missing=colander.drop)
    key2 = deferred_node


result = MySchema().bind().deserialize({'key-1': 'one', 'key-2': 'two'})
print(result)  # {'key-1': 'one'}
```

This is caused by the `__setitem__` code setting the name of the node to the name of the code variable.
https://github.com/Pylons/colander/blob/0e4e34ae32cb8cf926d7b4b28aa460caeb19ec69/src/colander/__init__.py#L2491

I'm not sure if it's just a matter of adding a check to not do anything if the node already has a name. That code is 8 years old at this point.
Though, I am also not sure how to create a workaround for my code block.

**Comment by Wim-De-Clercq** [comment]
update, I see this has very recently been adressed in https://github.com/Pylons/colander/commit/b5030d2a9184d29a9f46e69172a694b02f80d4b8
I'll have to wait for the next release I guess.

**Comment by bertjwregeer** [comment]
Hey @mmerickel can you do a release or would you like me to grab it?

**Comment by mmerickel** [comment]
1.8.3 is out now
