### ISSUE TITLE
conditional validation

### ISSUE THREAD

**Issue by marconi** [Pylons/colander#75]
How can I achieve conditional validation?

Say I have two fields field_a and field_b, field_b is optional by default but it becomes required when field_a has certain values.

I've been looking at the existing validators and it seems it only receives the node that it should validate, how can I access other nodes within the same schema from a validator?

**Comment by thruflo** [comment]
I'm over three years late to this thread but there is (now?!) another way to do this!

Use a deferred that conditionally returns `colander.required`:

```python
@colander.deferred
def conditionally_required(node, kw):
    some_condition = # whatever conditional logic you want
    if some_condition:
        return colander.drop # won't be required (or return a default like `None`)
    return colander.required # will be required
```

This can then be used as the `missing` value when defining a schema node:

```python
foo = colander.SchemaNode(
    colander.String(),
    missing=conditionally_required
)
```

As a concrete example, if you have the request bound to your schema as `kw['request']` and you wanted to make `foo` required unless a field called `action` has the value `cheat`, you could use:

```python
@colander.deferred
def required_unless_cheating(node, kw):
    request = kw['request']
    action = request.params.get('action')
    if action == 'cheat':
        return colander.drop
    return colander.required    
```
